apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURjeApNakUxTVRWYUZ3MDBNakE0TURjeE1qRTFNVFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDakR0RDlrL0o4bm0rUDlUbXB6dGpDeEpLcFdJZ0o1NjhuSFBzTGhQaFNGQVpOZS80dgpZSGxhQjk3OWRRbTJTRnZwd3BOYmxoK3RVZ3Z0b05sMkNUSUFiWE1YZWJOU3JrM1RkMTRISWJET1NSYlZaUFg2CmovNE9WM1EwQytWdDNYalNSME93RVNQak8zL254emErenlJN2c3M09lUzhLanRPZ2pkeWw1ZE9pZmRHa3RaU04KaDYwUy92ZFp5M1lRbWIvZE9zNTBNZ3lCS0pNN2F3c0VFNVFSMmF2Qk5lRHRrMTFudXFTb1NSamcyRVllcW9adwpyN3QzZVVCcXJVNWZ6a3FaZW8vZkZ2aUVDK2NMRE1md1NaRGVzSEtlRlE4cm5WbjQwU3JnWG95MStLWmZWL0grCjNqOTVWN3JwSG5xTW1wa2tuQW12cGJHNUtjd3E3RytuOEJVakFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFEOXV4b0lqZkhPdERFZVoyNwp3ajQ5bGM4Ym5UQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMWG1zN2pqYmNkclVQMGdqd2ZOZEdnMHpsU1hWCjlqNlFKWmdHYnlsa1lkdU1oMkVrYkJYY1NvOEpyQWJnTkthd09rZkFkSDVkaGhUK0IzZXVHZDdPUW10STg4NEIKKzBqaEJTV3Z2SUZqeFdLY3VuTnJtdkhTRjRrSWhDajk3ekxhTTZGM2QyNE5EVHYyOG10VEFoU2ZiVXhzU3lUcwplS1RQRjFOVlBqdUo3aDZ2WFVPajJFR0R2Um1DYWxPSFB4aFJhY1pMd3MwSjUwbEJFWnFONFhZdVprME91R0dVCk5KQ1NpK2tpWGlWM3UzRGNoR0MyMW9rK2FjcEtJYzRSRE9wZUJoZGZMYVJpK1lybXNXRkxQN0ErWTQwNUh5dUEKTnBSV2FYK3FnWlBtQkluNk5PbE9ud0ZuMCt1WXBsQ1l2bE9wSWpvV2U1ckJqYzNvZUJnc3YrWWRpUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b5f5c142-25b3-4080-aee0-0508a9eccb07.k8s.ondigitalocean.com
  name: do-nyc1-k8s-iniciativa
contexts:
- context:
    cluster: do-nyc1-k8s-iniciativa
    user: do-nyc1-k8s-iniciativa-admin
  name: do-nyc1-k8s-iniciativa
current-context: do-nyc1-k8s-iniciativa
users:
- name: do-nyc1-k8s-iniciativa-admin
  user:
    token: dop_v1_b2dbf9142d01c6c6287a08825bad69bffdd8075c0633b97b717e2027a164547c
